name: finance_manage
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  hugeicons: ^0.0.10



  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  assets:
    - asset/images/
    - asset/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: asset/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf

  uses-material-design: true

